[package]
name = "hello-bitris"
version = "0.1.0"
edition = "2021"
authors = ["knewjade"]

[dependencies]
#bitris = { git = "https://github.com/knewjade/bitris", branch = "develop" }
bitris = { path = "../bitris" }
itertools = "0.10.5"
bitvec = "1.0.1"
fxhash = "0.2.1"
tap = "1.0.1"
derive_more = "0.99.17"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }

[lib]
bench = false

#[profile.test]
#opt-level = 3
#debug = false

[[bench]]
name = "pc_rates"
harness = false
