on: [ push ]
name: tests
jobs:
  build_and_test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: run tests for core
        run: cargo test --release && cargo test --benches
      - name: run tests for acceptance tests
        run: cargo test --release
        working-directory: ./acceptance_tests
      - name: run tests for example
        run: cargo test --release
        working-directory: ./example
